# Nombre del workflow que aparecerá en la pestaña "Actions" de GitHub
name: Python Tests

# Configura cuándo se debe ejecutar este workflow
on:
  # Ejecutar en cada push a la rama 'main'
  push:
    branches: [ "main" ]
  # Ejecutar también en cada pull request que apunte a la rama 'main'
  pull_request:
    branches: [ "main" ]

# Define los trabajos (jobs) que se ejecutarán. En este caso, solo uno.
jobs:
  build:
    # El tipo de máquina virtual donde se ejecutarán las pruebas. 'ubuntu-latest' es la más común.
    runs-on: ubuntu-latest

    # Los pasos que se ejecutarán en orden
    steps:
    # Paso 1: Clona tu repositorio en la máquina virtual
    - name: Check out repository code
      uses: actions/checkout@v4

    # Paso 2: Configura el entorno de Python (puedes cambiar la versión si lo necesitas)
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # Paso 3: Instala las dependencias de tu proyecto
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Paso 4: Ejecuta las pruebas usando pytest
    # Pytest detectará automáticamente tu archivo 'testProject.py'.
    - name: Run tests with pytest
      run: |
        pytest
    - name: Log in Docker
      if github.event == 'push'
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: build and push docker
      if github.event == 'push'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}
    - name: tirgger render deploy
      if github.event == 'push'
      run: |
        curl -X POST ${{secrets.RENDER_DEPLY_HOOK}}
