# Nombre del workflow
name: Python Tests and Deploy

# Configura cu√°ndo se debe ejecutar
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout
    - name: Check out repository code
      uses: actions/checkout@v4

    # Paso 2: Setup Python
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # Paso 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Paso 4: Run tests
    - name: Run tests with pytest
      run: |
        pytest

    # --- FASE DE DESPLIEGUE ---

    # Paso 5: Login en Docker Hub
    - name: Log in to Docker Hub
      if: github.event_name == 'push'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Paso 6: Build & Push
    - name: Build and push Docker image
      if: github.event_name == 'push'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/fastfeast-api:latest

    # Paso 7: Deploy en Render
    - name: Trigger Render Deploy
      if: github.event_name == 'push'
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

#test3
